### ISSUE TITLE
SalesforceSharp 1.1.0 is not compatible with HelperSharp 0.0.4.2

### ISSUE THREAD

**Issue by Paqi** [giacomelli/SalesforceSharp#42]
[SalesforceSharp 1.1.0](https://www.nuget.org/packages/SalesforceSharp/) is supposed to be compatible with any version of `HelperSharp` >= `0.0.4.1`. 

Our project uses `HelperSharp 0.0.4.2`. Everything builds fine, and our package manager doesn't complain when resolving package versions, but we're seeing the following runtime error:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'HelperSharp, Version=1.0.5358.23405, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at SalesforceSharp.Security.UsernamePasswordAuthenticationFlow..ctor(IRestClient restClient, String clientId, String clientSecret, String username, String password, String tokenRequestEndpointUrl)
   at SalesforceSharp.Security.UsernamePasswordAuthenticationFlow..ctor(String clientId, String clientSecret, String username, String password, String tokenRequestEndpointUrl) in C:\projects\salesforcesharp\src\SalesforceSharp\Security\UsernamePasswordAuthenticationFlow.cs:line 56
```

`HelperSharp, Version=1.0.5358.23405` corresponds to  `HelperSharp 0.0.4.1`.

The projects files might have to be updated to use ProjectReference nodes instead of regular Reference nodes: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning

**Comment by Sharky99x** [comment]
This has just started happening for me the last few days too.

I am also getting the error :


Could not load file or assembly 'RestSharp,   Version=105.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its   dependencies. The system cannot find the file specified.
--

My project was using RestSharp v106.11.7 and once I downgraded this to v105.0.1 then I received your error above for HelperSharp.

I tend to like to keep everything running on the latest stable versions.  So I hope this is something that can be fixed quickly soon.

**Comment by sbobowski** [comment]
> I tend to like to keep everything running on the latest stable versions. So I hope this is something that can be fixed quickly soon.

Me too, but 5 months in and nothing :(
